name: Bug Report
description: Report a bug in mlflow-modal
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: mlflow-modal-version
    attributes:
      label: mlflow-modal version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: mlflow-version
    attributes:
      label: MLflow version
      placeholder: "2.10.0"
    validations:
      required: true

  - type: input
    id: modal-version
    attributes:
      label: Modal SDK version
      placeholder: "0.64.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.10"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Code or steps to reproduce the behavior.
      placeholder: |
        ```python
        from mlflow.deployments import get_deploy_client
        client = get_deploy_client("modal")
        # ...
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs / stack trace
      description: Paste any relevant logs or error messages.
      render: shell
